# Generated by Django 3.1.2 on 2020-10-23 20:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controlasist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=35, verbose_name='Prestanción')),
                ('num_dias', models.IntegerField(verbose_name='Dias')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoContratacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=100, verbose_name='Tipo de contratación')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=15, verbose_name='Turno')),
                ('dia_trab', models.CharField(max_length=100, verbose_name='Dias que labora')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=25, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=25, verbose_name='Apellido Materno')),
                ('fecha_nac', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('curp', models.CharField(max_length=18, verbose_name='C.U.R.P.')),
                ('rfc', models.CharField(max_length=13, verbose_name='R.F.C.')),
                ('num_empleado', models.IntegerField(unique=True, verbose_name='N° Empleado')),
                ('num_plaza', models.IntegerField(verbose_name='N° Plaza')),
                ('nivel', models.IntegerField(verbose_name='Nivel')),
                ('universo', models.CharField(max_length=2, verbose_name='Universo')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('zona_pagadora', models.IntegerField(verbose_name='Zona Pagadora')),
                ('codigo_puesto', models.CharField(max_length=10, verbose_name='Codigo de puesto')),
                ('secc_sindical', models.IntegerField(verbose_name='Sección Sindical')),
                ('faltas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlasist.faltas')),
                ('prestaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.prestaciones')),
                ('tipo_contratacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.tipocontratacion')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.turno')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
            },
        ),
    ]
