# Generated by Django 3.1.2 on 2020-10-24 05:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('controlasist', '0002_auto_20201024_0501'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=25, verbose_name='Codigo de Puesto')),
            ],
            options={
                'verbose_name': 'Codigo de Puesto',
                'verbose_name_plural': 'Codigos de Puestos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Dias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=25, verbose_name='Dias Laborales')),
            ],
            options={
                'verbose_name': 'Dia Laboral',
                'verbose_name_plural': 'Dias Laborales',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NivelSalarial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nivel', models.IntegerField(verbose_name='Nivel Salarial')),
            ],
            options={
                'verbose_name': 'Nivel Salarial',
                'verbose_name_plural': 'Niveles Salariales',
                'ordering': ['nivel'],
            },
        ),
        migrations.CreateModel(
            name='SeccionSindical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=35, verbose_name='Prestanción')),
                ('seccion', models.IntegerField(verbose_name='Dias')),
            ],
            options={
                'verbose_name': 'Seccion Sindical',
                'verbose_name_plural': 'Secciones Sindicales',
                'ordering': ['seccion'],
            },
        ),
        migrations.CreateModel(
            name='Universo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=10, verbose_name='Universo')),
            ],
            options={
                'verbose_name': 'Universo',
                'verbose_name_plural': 'Universos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ZonaPagadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=10, verbose_name='Universo')),
            ],
            options={
                'verbose_name': 'Zona Pagadora',
                'verbose_name_plural': 'Zonas Pagadoras',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='personal',
            options={'ordering': ['apellido_paterno'], 'verbose_name': 'Personal', 'verbose_name_plural': 'Personal'},
        ),
        migrations.AlterModelOptions(
            name='prestaciones',
            options={'ordering': ['id'], 'verbose_name': 'Prestacion', 'verbose_name_plural': 'Prestaciones'},
        ),
        migrations.AlterModelOptions(
            name='tipocontratacion',
            options={'ordering': ['id'], 'verbose_name': 'Tipo de Contratación', 'verbose_name_plural': 'Tipos de Contratación'},
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['id'], 'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
        migrations.AddField(
            model_name='personal',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='faltas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas_personal', to='controlasist.faltas'),
        ),
        migrations.RemoveField(
            model_name='turno',
            name='dia_trab',
        ),
        migrations.AlterUniqueTogether(
            name='personal',
            unique_together={('num_empleado',)},
        ),
        migrations.AlterField(
            model_name='personal',
            name='codigo_puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.codigopuesto'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.nivelsalarial'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='secc_sindical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.seccionsindical'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='universo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.universo'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='zona_pagadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.zonapagadora'),
        ),
        migrations.AddField(
            model_name='turno',
            name='dia_trab',
            field=models.ManyToManyField(to='personal.Dias'),
        ),
    ]
