# Generated by Django 3.1.2 on 2020-10-25 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
        ('personal', '0002_auto_20201024_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='dia_trab',
        ),
        migrations.AlterField(
            model_name='personal',
            name='codigo_puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.codigopuesto'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.nivelsalarial'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='prestaciones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.prestaciones'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='secc_sindical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.seccionsindical'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='tipo_contratacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.tipocontratacion'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.turno'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='universo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.universo'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='zona_pagadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.zonapagadora'),
        ),
        migrations.DeleteModel(
            name='CodigoPuesto',
        ),
        migrations.DeleteModel(
            name='Dias',
        ),
        migrations.DeleteModel(
            name='NivelSalarial',
        ),
        migrations.DeleteModel(
            name='Prestaciones',
        ),
        migrations.DeleteModel(
            name='SeccionSindical',
        ),
        migrations.DeleteModel(
            name='TipoContratacion',
        ),
        migrations.DeleteModel(
            name='Turno',
        ),
        migrations.DeleteModel(
            name='Universo',
        ),
        migrations.DeleteModel(
            name='ZonaPagadora',
        ),
    ]
