# Generated by Django 3.1.2 on 2020-10-25 00:34

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=25, verbose_name='Codigo de Puesto')),
            ],
            options={
                'verbose_name': 'Codigo de Puesto',
                'verbose_name_plural': 'Codigos de Puestos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Dias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=25, verbose_name='Dias Laborales')),
            ],
            options={
                'verbose_name': 'Dia Laboral',
                'verbose_name_plural': 'Dias Laborales',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NivelSalarial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nivel', models.IntegerField(verbose_name='Nivel Salarial')),
            ],
            options={
                'verbose_name': 'Nivel Salarial',
                'verbose_name_plural': 'Niveles Salariales',
                'ordering': ['nivel'],
            },
        ),
        migrations.CreateModel(
            name='Prestaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=35, verbose_name='Prestanción')),
                ('num_dias', models.IntegerField(verbose_name='Dias')),
            ],
            options={
                'verbose_name': 'Prestacion',
                'verbose_name_plural': 'Prestaciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SeccionSindical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=35, verbose_name='Prestanción')),
                ('seccion', models.IntegerField(verbose_name='Dias')),
            ],
            options={
                'verbose_name': 'Seccion Sindical',
                'verbose_name_plural': 'Secciones Sindicales',
                'ordering': ['seccion'],
            },
        ),
        migrations.CreateModel(
            name='TipoContratacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=100, verbose_name='Tipo de contratación')),
            ],
            options={
                'verbose_name': 'Tipo de Contratación',
                'verbose_name_plural': 'Tipos de Contratación',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Universo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=10, verbose_name='Universo')),
            ],
            options={
                'verbose_name': 'Universo',
                'verbose_name_plural': 'Universos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ZonaPagadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=10, verbose_name='Universo')),
            ],
            options={
                'verbose_name': 'Zona Pagadora',
                'verbose_name_plural': 'Zonas Pagadoras',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=15, verbose_name='Turno')),
                ('dia_trab', models.ManyToManyField(to='admins.Dias')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['id'],
            },
        ),
    ]
