# Generated by Django 3.1.2 on 2020-11-03 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
        ('controlasist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faltas',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Personal', to='personal.personal'),
        ),
    ]
